apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gaia-air-deny-all
  namespace: gaia-air
spec:
  egress: []
  ingress: []
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
