component:
  id: CI-AE002
  name: EcsConfiguration
  version: v1.0
configuration:
  diagnostic_parameters: {}
  interface_settings: {}
  operational_parameters: {}
  safety_limits: {}
validation:
  acceptance_criteria: []
  test_scenarios: []
  verification_methods: []
